# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    allow:
      # Allow updates for dataclasses as this is only <3.7 ... see how this behaves: https://github.blog/changelog/2023-08-17-deprecation-dependabot-updates-drop-support-for-python-3-6-and-3-7/
      - dependency-name: "dataclasses"
    schedule:
      interval: "weekly"
